### ISSUE TITLE
Create service does not have confirmation

### ISSUE THREAD

**Issue by jwf1112** [steevejoseph/bazaar-backend#11]
just returns a list of services, with no confirmation that the service was created makeing it hard to test if a service was actually created

**Comment by steevejoseph** [comment]
Not sure that this is a bug, I wrote that as intended behavior. Indication of confirmation _should_ come from an (unstyled/plaintext) flash message at the top. The (reused) EJS file I redirect to expects only a param called `services`.

For testing, feel free to change:

```javascript
 var services = body.services;
 req.flash("success", "Service added!");
return res.render('services/index.ejs', {services:services});
```

to 

```javascript
var services = body.services;
var service = body.service;

req.flash("success", "Service added!");
return res.render('services/index.ejs', {service:service});
```
This'll render the page with **just** the newly created service.

We won't be using anything in the **/routes**, **/views**, or **/public** directory for actual frontend, that'll be all Reactjs, so everything in there is essentially deprecated. Rather than blasting them completely, I figured we'd keep them for some quick "give this" --> "get that back" --> "render that" testing from within the API server, without having to take the time to `create-react-app` or define a set of components.
